/** P1 Event funnel demo data — masked tokens only */
const EVENT_SUMMARY = {
  eventName: "CRE Finance Summit 2025",
  platform: "Event Platform",
  totalAttendees: 2211,
  qualifiedCount: 145,
  priorityTargetCount: 25,
  extractionDate: "2025-11-14",
  sourceLabel: "Event attendee export (demo tokens only)",
};

const ATTENDEE_CATEGORIES = [
  { category: "CRE Broker / Advisor", count: 412, pct: 18.6 },
  { category: "Lender / Capital Markets", count: 318, pct: 14.4 },
  { category: "Investor / Sponsor", count: 287, pct: 13.0 },
  { category: "Vendor / PropTech", count: 524, pct: 23.7 },
  { category: "Government / Association", count: 198, pct: 9.0 },
  { category: "Other / Unclassified", count: 472, pct: 21.3 },
];

const CLASSIFICATION_STATS = { creBroker: 412, lender: 318, qualifiedCre: 145, excluded: 2066 };

const CLASSIFICATION_SAMPLES = [
  { id: "evt-s01", name: "Alex R.", company: "Walker & Dunlop", title: "SVP, Capital Markets", category: "CRE Broker / Advisor", confidence: "High", creSignal: "Multifamily debt advisory" },
  { id: "evt-s02", name: "Priya K.", company: "JLL", title: "Director, Debt & Structured Finance", category: "CRE Broker / Advisor", confidence: "High", creSignal: "Office & industrial placements" },
  { id: "evt-s03", name: "Tom H.", company: "Newmark", title: "Managing Director", category: "CRE Broker / Advisor", confidence: "High", creSignal: "Bridge & perm financing" },
  { id: "evt-s04", name: "Lena M.", company: "CBRE", title: "Executive Director", category: "CRE Broker / Advisor", confidence: "Medium", creSignal: "National agency lending" },
  { id: "evt-s05", name: "Chris D.", company: "Marcus & Millichap", title: "First VP", category: "CRE Broker / Advisor", confidence: "High", creSignal: "Small balance multifamily" },
  { id: "evt-s06", name: "Nina S.", company: "Berkadia", title: "Senior Director", category: "Lender / Capital Markets", confidence: "Medium", creSignal: "Agency multifamily" },
  { id: "evt-s07", name: "Omar F.", company: "KeyBank", title: "VP, Commercial Mortgage", category: "Lender / Capital Markets", confidence: "Medium", creSignal: "Balance sheet CRE" },
  { id: "evt-s08", name: "Rachel W.", company: "Colliers", title: "Principal", category: "CRE Broker / Advisor", confidence: "High", creSignal: "Retail & mixed-use debt" },
  { id: "evt-s09", name: "Dan P.", company: "Eastdil Secured", title: "Managing Director", category: "CRE Broker / Advisor", confidence: "High", creSignal: "Large loan syndications" },
  { id: "evt-s10", name: "Sofia L.", company: "Eastdil Secured", title: "Director", category: "CRE Broker / Advisor", confidence: "High", creSignal: "Institutional placements" },
  { id: "evt-s11", name: "Mike B.", company: "LoanLogics", title: "Account Executive", category: "Vendor / PropTech", confidence: "High", creSignal: "Not CRE producer" },
  { id: "evt-s12", name: "Jen C.", company: "MBA", title: "Policy Analyst", category: "Government / Association", confidence: "High", creSignal: "Not broker" },
];

const QUALIFIED_PROSPECTS = [
  { id: "evt-q01", name: "Alex R.", company: "Walker & Dunlop", state: "TX", category: "CRE Broker / Advisor", creRole: "Capital Markets", scoreHint: 88 },
  { id: "evt-q02", name: "Priya K.", company: "JLL", state: "CA", category: "CRE Broker / Advisor", creRole: "Debt Advisory", scoreHint: 91 },
  { id: "evt-q03", name: "Tom H.", company: "Newmark", state: "NY", category: "CRE Broker / Advisor", creRole: "Debt & Equity", scoreHint: 86 },
  { id: "evt-q04", name: "Lena M.", company: "CBRE", state: "IL", category: "CRE Broker / Advisor", creRole: "Agency Lending", scoreHint: 84 },
  { id: "evt-q05", name: "Chris D.", company: "Marcus & Millichap", state: "AZ", category: "CRE Broker / Advisor", creRole: "Investment Sales Finance", scoreHint: 79 },
  { id: "evt-q06", name: "Rachel W.", company: "Colliers", state: "FL", category: "CRE Broker / Advisor", creRole: "Debt Advisory", scoreHint: 82 },
  { id: "evt-q07", name: "Dan P.", company: "Eastdil Secured", state: "NY", category: "CRE Broker / Advisor", creRole: "Capital Markets", scoreHint: 90 },
  { id: "evt-q08", name: "Sofia L.", company: "Eastdil Secured", state: "CA", category: "CRE Broker / Advisor", creRole: "Structured Finance", scoreHint: 87 },
  { id: "evt-q09", name: "Kevin M.", company: "Northmarq", state: "MN", category: "CRE Broker / Advisor", creRole: "Debt Placement", scoreHint: 85 },
  { id: "evt-q10", name: "Hannah T.", company: "PGIM", state: "NJ", category: "CRE Broker / Advisor", creRole: "Agency Production", scoreHint: 80 },
  { id: "evt-q11", name: "Greg F.", company: "Arbor Realty", state: "NY", category: "CRE Broker / Advisor", creRole: "Multifamily Lending", scoreHint: 83 },
  { id: "evt-q12", name: "Ivy N.", company: "Greystone", state: "NY", category: "CRE Broker / Advisor", creRole: "FHA / Agency", scoreHint: 81 },
  { id: "evt-q13", name: "Paul S.", company: "Bellwether", state: "CA", category: "CRE Broker / Advisor", creRole: "Bridge Lending", scoreHint: 78 },
  { id: "evt-q14", name: "Maya J.", company: "Ready Capital", state: "NY", category: "CRE Broker / Advisor", creRole: "Small Balance", scoreHint: 76 },
  { id: "evt-q15", name: "Ethan W.", company: "Hunt Mortgage", state: "FL", category: "CRE Broker / Advisor", creRole: "Agency Multifamily", scoreHint: 77 },
  { id: "evt-q16", name: "Olivia B.", company: "CBRE", state: "TX", category: "CRE Broker / Advisor", creRole: "Production", scoreHint: 86 },
  { id: "evt-q17", name: "Noah C.", company: "JLL", state: "WA", category: "CRE Broker / Advisor", creRole: "Debt Advisory", scoreHint: 84 },
  { id: "evt-q18", name: "Ava D.", company: "Newmark", state: "CO", category: "CRE Broker / Advisor", creRole: "Capital Markets", scoreHint: 82 },
  { id: "evt-q19", name: "Liam E.", company: "Walker & Dunlop", state: "GA", category: "CRE Broker / Advisor", creRole: "Production", scoreHint: 88 },
  { id: "evt-q20", name: "Emma G.", company: "Colliers", state: "NC", category: "CRE Broker / Advisor", creRole: "Debt Placement", scoreHint: 80 },
];

const PRIORITY_TARGETS_RAW = [
  {
    "id": "evt-brk-001",
    "name": "Marcus Whitfield",
    "company": "CBRE Capital Markets",
    "state": "TX",
    "city": "Dallas",
    "email": "mwhitfield@cbre.com",
    "phone": "(214) 555-0182",
    "lastEmployer": "CBRE Capital Markets",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "18",
    "volume2025": "$450M+",
    "linkedin": "https://linkedin.com/in/marcuswhitfield-cre",
    "activityLevel": "High",
    "dealSignals": "Closed $85M Dallas office portfolio refi (Q1 2025); $42M industrial acquisition loan (Nov 2024)",
    "affiliations": "CCIM, MBA, ULI",
    "personalizationHook": "Recently closed an $85M Dallas office portfolio refinancing.",
    "confidence": "High",
    "evidenceNotes": "Verified via CBRE team page, NMLS, and LinkedIn.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "CBRE Team Page",
        "url": "https://www.cbre.com/people/marcus-whitfield",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 92,
    "sourcePlatform": "GRIP",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q01"
  },
  {
    "id": "evt-brk-002",
    "name": "Jennifer Alvarez",
    "company": "JLL Debt Advisory",
    "state": "CA",
    "city": "Los Angeles",
    "email": "jennifer.alvarez@jll.com",
    "phone": "(310) 555-0247",
    "lastEmployer": "JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "14",
    "volume2025": "$320M",
    "linkedin": "https://linkedin.com/in/jennifer-alvarez-cre",
    "activityLevel": "High",
    "dealSignals": "$62M multifamily bridge loan (Jan 2025); $28M retail center permanent financing (Sep 2024)",
    "affiliations": "MBA, ICSC, ULI",
    "personalizationHook": "Recently closed a $62M multifamily bridge loan in Southern California.",
    "confidence": "High",
    "evidenceNotes": "JLL bio page and California DRE license verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "JLL Bio Page",
        "url": "https://www.us.jll.com/en/people/jennifer-alvarez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 91,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q02"
  },
  {
    "id": "evt-brk-003",
    "name": "David Chen",
    "company": "Walker & Dunlop",
    "state": "NY",
    "city": "New York",
    "email": "dchen@walkerdunlop.com",
    "phone": "(212) 555-0391",
    "lastEmployer": "Walker & Dunlop",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "22",
    "volume2025": "$580M+",
    "linkedin": "https://linkedin.com/in/davidchen-cre",
    "activityLevel": "High",
    "dealSignals": "$120M Manhattan mixed-use refinancing (Feb 2025); Speaker at CREF Summit 2024",
    "affiliations": "CCIM, MBA, SIOR",
    "personalizationHook": "Speaker at CREF Summit 2024; closed $120M Manhattan mixed-use refinancing.",
    "confidence": "High",
    "evidenceNotes": "Walker & Dunlop team page and CREF Summit speaker listing.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Walker & Dunlop Team",
        "url": "https://www.walkerdunlop.com/team/david-chen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 90,
    "sourcePlatform": "Brella",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q03"
  },
  {
    "id": "evt-brk-004",
    "name": "Rachel Thompson",
    "company": "Newmark",
    "state": "FL",
    "city": "Miami",
    "email": "rthompson@nmrk.com",
    "phone": "(305) 555-0564",
    "lastEmployer": "Newmark",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "9",
    "volume2025": "$180M",
    "linkedin": "https://linkedin.com/in/rachel-thompson-cre",
    "activityLevel": "Medium",
    "dealSignals": "$35M hospitality acquisition loan (Dec 2024)",
    "affiliations": "MBA, ULI",
    "personalizationHook": "Recently closed a $35M hospitality acquisition loan in South Florida.",
    "confidence": "High",
    "evidenceNotes": "Newmark team page and Florida licensing verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Newmark Team Page",
        "url": "https://www.nmrk.com/people/rachel-thompson",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 89,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q04"
  },
  {
    "id": "evt-brk-005",
    "name": "Michael O'Brien",
    "company": "Berkadia",
    "state": "IL",
    "city": "Chicago",
    "email": "mobrien@berkadia.com",
    "phone": "(312) 555-0718",
    "lastEmployer": "Berkadia",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "16",
    "volume2025": "$275M",
    "linkedin": "https://linkedin.com/in/michael-obrien-cre",
    "activityLevel": "Medium",
    "dealSignals": "$48M affordable housing FHA loan (Oct 2024)",
    "affiliations": "MBA, CCIM",
    "personalizationHook": "Specializes in affordable housing FHA \u2014 closed $48M deal in Q4 2024.",
    "confidence": "High",
    "evidenceNotes": "Berkadia bio and HUD FHA announcement.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Berkadia Profile",
        "url": "https://www.berkadia.com/people/michael-obrien",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 88,
    "sourcePlatform": "GRIP",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q05"
  },
  {
    "id": "evt-brk-006",
    "name": "Priya Sharma",
    "company": "HFF (JLL)",
    "state": "GA",
    "city": "Atlanta",
    "email": "psharma@jll.com",
    "phone": "(404) 555-0833",
    "lastEmployer": "HFF / JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "11",
    "volume2025": "$210M",
    "linkedin": "https://linkedin.com/in/priya-sharma-cre",
    "activityLevel": "High",
    "dealSignals": "$55M industrial portfolio refinancing (Mar 2025)",
    "affiliations": "CCIM, SIOR, MBA",
    "personalizationHook": "Recently closed a $55M industrial portfolio refinancing in Atlanta.",
    "confidence": "High",
    "evidenceNotes": "JLL team page and CCIM member directory.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "JLL Team Page",
        "url": "https://www.us.jll.com/en/people/priya-sharma",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 87,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q06"
  },
  {
    "id": "evt-brk-007",
    "name": "James Rodriguez",
    "company": "Marcus & Millichap Capital",
    "state": "AZ",
    "city": "Phoenix",
    "email": "jrodriguez@marcusmillichap.com",
    "phone": "(602) 555-0946",
    "lastEmployer": "Marcus & Millichap",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "7",
    "volume2025": "$95M",
    "linkedin": "https://linkedin.com/in/james-rodriguez-cre",
    "activityLevel": "Medium",
    "dealSignals": "$18M self-storage acquisition financing (Aug 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Active in Phoenix self-storage \u2014 closed $18M acquisition financing.",
    "confidence": "Medium",
    "evidenceNotes": "M&M team page verified. Volume from partial disclosures.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "M&M Bio",
        "url": "https://www.marcusmillichap.com/advisors/james-rodriguez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 86,
    "sourcePlatform": "Brella",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q07"
  },
  {
    "id": "evt-brk-008",
    "name": "Sarah Kim",
    "company": "Eastdil Secured",
    "state": "WA",
    "city": "Seattle",
    "email": "skim@eastdil.com",
    "phone": "(206) 555-1029",
    "lastEmployer": "Eastdil Secured",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "13",
    "volume2025": "$390M+",
    "linkedin": "https://linkedin.com/in/sarah-kim-cre",
    "activityLevel": "High",
    "dealSignals": "$95M Seattle tech campus debt placement (Jan 2025)",
    "affiliations": "MBA, ULI, CCIM",
    "personalizationHook": "Recently placed $95M debt on a Seattle tech campus.",
    "confidence": "High",
    "evidenceNotes": "Eastdil team page and press releases.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Eastdil Secured Team",
        "url": "https://www.eastdilsecured.com/people/sarah-kim",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 85,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q08"
  },
  {
    "id": "evt-brk-009",
    "name": "Robert Hayes",
    "company": "Colliers Mortgage",
    "state": "CO",
    "city": "Denver",
    "email": "rhayes@colliers.com",
    "phone": "(303) 555-1157",
    "lastEmployer": "Colliers Mortgage",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "10",
    "volume2025": "Not Publicly Disclosed",
    "linkedin": "https://linkedin.com/in/robert-hayes-cre",
    "activityLevel": "Low",
    "dealSignals": "No recent deal signals found in last 12 months",
    "affiliations": "MBA",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Medium",
    "evidenceNotes": "Colliers team page confirms employment. Volume unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Volume not publicly disclosed; no recent deal signals",
    "rowStatus": "Review Required",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Colliers Team",
        "url": "https://www.colliers.com/en/people/robert-hayes",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 84,
    "sourcePlatform": "GRIP",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q09"
  },
  {
    "id": "evt-brk-010",
    "name": "Amanda Foster",
    "company": "Northmarq",
    "state": "MN",
    "city": "Minneapolis",
    "email": "afoster@northmarq.com",
    "phone": "(612) 555-1284",
    "lastEmployer": "Northmarq",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "8",
    "volume2025": "$140M",
    "linkedin": "https://linkedin.com/in/amanda-foster-cre",
    "activityLevel": "Medium",
    "dealSignals": "$22M multifamily agency loan (Jul 2024)",
    "affiliations": "MBA, ICSC",
    "personalizationHook": "Recently closed a $22M multifamily agency loan in Twin Cities.",
    "confidence": "High",
    "evidenceNotes": "Northmarq bio and Freddie Mac lender list.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Northmarq Profile",
        "url": "https://www.northmarq.com/people/amanda-foster",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 83,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q10"
  },
  {
    "id": "evt-brk-011",
    "name": "Thomas Wright",
    "company": "Greystone",
    "state": "NC",
    "city": "Charlotte",
    "email": "twright@greystone.com",
    "phone": "(704) 555-1392",
    "lastEmployer": "Unknown",
    "onlyCreMortgage": "Unverified \u2014 Manual Review",
    "yearsInCre": "Unknown",
    "volume2025": "Unknown",
    "linkedin": "Not Publicly Listed",
    "activityLevel": "Unknown",
    "dealSignals": "No deal signals found",
    "affiliations": "None identified",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Low",
    "evidenceNotes": "Only Tier 3 aggregator source found. Identity unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Identity unverified \u2014 only Tier 3 aggregator source",
    "rowStatus": "No Match",
    "scoreInputs": {
      "fullTimeCre": false,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "CRE Aggregator",
        "url": "https://www.loopnet.com/commercial-brokers/thomas-wright",
        "tier": 3
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 82,
    "sourcePlatform": "Brella",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q11"
  },
  {
    "id": "evt-brk-012",
    "name": "Lisa Nguyen",
    "company": "Arbor Realty Trust",
    "state": "NV",
    "city": "Las Vegas",
    "email": "lnguyen@arbor.com",
    "phone": "(702) 555-1468",
    "lastEmployer": "Arbor Realty Trust",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "6",
    "volume2025": "$75M",
    "linkedin": "https://linkedin.com/in/lisa-nguyen-cre",
    "activityLevel": "Medium",
    "dealSignals": "$15M multifamily loan (May 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Recently closed a $15M multifamily loan in Las Vegas.",
    "confidence": "Medium",
    "evidenceNotes": "Arbor team page verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Arbor Realty Team",
        "url": "https://www.arbor.com/team/lisa-nguyen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 81,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q12"
  },
  {
    "id": "evt-brk-013",
    "name": "Marcus Whitfield",
    "company": "CBRE Capital Markets",
    "state": "TX",
    "city": "Dallas",
    "email": "mwhitfield@cbre.com",
    "phone": "(214) 555-0182",
    "lastEmployer": "CBRE Capital Markets",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "18",
    "volume2025": "$450M+",
    "linkedin": "https://linkedin.com/in/marcuswhitfield-cre",
    "activityLevel": "High",
    "dealSignals": "Closed $85M Dallas office portfolio refi (Q1 2025); $42M industrial acquisition loan (Nov 2024)",
    "affiliations": "CCIM, MBA, ULI",
    "personalizationHook": "Recently closed an $85M Dallas office portfolio refinancing.",
    "confidence": "High",
    "evidenceNotes": "Verified via CBRE team page, NMLS, and LinkedIn.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "CBRE Team Page",
        "url": "https://www.cbre.com/people/marcus-whitfield",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 80,
    "sourcePlatform": "GRIP",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q13"
  },
  {
    "id": "evt-brk-014",
    "name": "Jennifer Alvarez",
    "company": "JLL Debt Advisory",
    "state": "CA",
    "city": "Los Angeles",
    "email": "jennifer.alvarez@jll.com",
    "phone": "(310) 555-0247",
    "lastEmployer": "JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "14",
    "volume2025": "$320M",
    "linkedin": "https://linkedin.com/in/jennifer-alvarez-cre",
    "activityLevel": "High",
    "dealSignals": "$62M multifamily bridge loan (Jan 2025); $28M retail center permanent financing (Sep 2024)",
    "affiliations": "MBA, ICSC, ULI",
    "personalizationHook": "Recently closed a $62M multifamily bridge loan in Southern California.",
    "confidence": "High",
    "evidenceNotes": "JLL bio page and California DRE license verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "JLL Bio Page",
        "url": "https://www.us.jll.com/en/people/jennifer-alvarez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 79,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q14"
  },
  {
    "id": "evt-brk-015",
    "name": "David Chen",
    "company": "Walker & Dunlop",
    "state": "NY",
    "city": "New York",
    "email": "dchen@walkerdunlop.com",
    "phone": "(212) 555-0391",
    "lastEmployer": "Walker & Dunlop",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "22",
    "volume2025": "$580M+",
    "linkedin": "https://linkedin.com/in/davidchen-cre",
    "activityLevel": "High",
    "dealSignals": "$120M Manhattan mixed-use refinancing (Feb 2025); Speaker at CREF Summit 2024",
    "affiliations": "CCIM, MBA, SIOR",
    "personalizationHook": "Speaker at CREF Summit 2024; closed $120M Manhattan mixed-use refinancing.",
    "confidence": "High",
    "evidenceNotes": "Walker & Dunlop team page and CREF Summit speaker listing.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Walker & Dunlop Team",
        "url": "https://www.walkerdunlop.com/team/david-chen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 78,
    "sourcePlatform": "Brella",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q15"
  },
  {
    "id": "evt-brk-016",
    "name": "Rachel Thompson",
    "company": "Newmark",
    "state": "FL",
    "city": "Miami",
    "email": "rthompson@nmrk.com",
    "phone": "(305) 555-0564",
    "lastEmployer": "Newmark",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "9",
    "volume2025": "$180M",
    "linkedin": "https://linkedin.com/in/rachel-thompson-cre",
    "activityLevel": "Medium",
    "dealSignals": "$35M hospitality acquisition loan (Dec 2024)",
    "affiliations": "MBA, ULI",
    "personalizationHook": "Recently closed a $35M hospitality acquisition loan in South Florida.",
    "confidence": "High",
    "evidenceNotes": "Newmark team page and Florida licensing verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Newmark Team Page",
        "url": "https://www.nmrk.com/people/rachel-thompson",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 77,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q16"
  },
  {
    "id": "evt-brk-017",
    "name": "Michael O'Brien",
    "company": "Berkadia",
    "state": "IL",
    "city": "Chicago",
    "email": "mobrien@berkadia.com",
    "phone": "(312) 555-0718",
    "lastEmployer": "Berkadia",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "16",
    "volume2025": "$275M",
    "linkedin": "https://linkedin.com/in/michael-obrien-cre",
    "activityLevel": "Medium",
    "dealSignals": "$48M affordable housing FHA loan (Oct 2024)",
    "affiliations": "MBA, CCIM",
    "personalizationHook": "Specializes in affordable housing FHA \u2014 closed $48M deal in Q4 2024.",
    "confidence": "High",
    "evidenceNotes": "Berkadia bio and HUD FHA announcement.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Berkadia Profile",
        "url": "https://www.berkadia.com/people/michael-obrien",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 76,
    "sourcePlatform": "GRIP",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q17"
  },
  {
    "id": "evt-brk-018",
    "name": "Priya Sharma",
    "company": "HFF (JLL)",
    "state": "GA",
    "city": "Atlanta",
    "email": "psharma@jll.com",
    "phone": "(404) 555-0833",
    "lastEmployer": "HFF / JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "11",
    "volume2025": "$210M",
    "linkedin": "https://linkedin.com/in/priya-sharma-cre",
    "activityLevel": "High",
    "dealSignals": "$55M industrial portfolio refinancing (Mar 2025)",
    "affiliations": "CCIM, SIOR, MBA",
    "personalizationHook": "Recently closed a $55M industrial portfolio refinancing in Atlanta.",
    "confidence": "High",
    "evidenceNotes": "JLL team page and CCIM member directory.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "JLL Team Page",
        "url": "https://www.us.jll.com/en/people/priya-sharma",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 92,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q18"
  },
  {
    "id": "evt-brk-019",
    "name": "James Rodriguez",
    "company": "Marcus & Millichap Capital",
    "state": "AZ",
    "city": "Phoenix",
    "email": "jrodriguez@marcusmillichap.com",
    "phone": "(602) 555-0946",
    "lastEmployer": "Marcus & Millichap",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "7",
    "volume2025": "$95M",
    "linkedin": "https://linkedin.com/in/james-rodriguez-cre",
    "activityLevel": "Medium",
    "dealSignals": "$18M self-storage acquisition financing (Aug 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Active in Phoenix self-storage \u2014 closed $18M acquisition financing.",
    "confidence": "Medium",
    "evidenceNotes": "M&M team page verified. Volume from partial disclosures.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "M&M Bio",
        "url": "https://www.marcusmillichap.com/advisors/james-rodriguez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 91,
    "sourcePlatform": "Brella",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q19"
  },
  {
    "id": "evt-brk-020",
    "name": "Sarah Kim",
    "company": "Eastdil Secured",
    "state": "WA",
    "city": "Seattle",
    "email": "skim@eastdil.com",
    "phone": "(206) 555-1029",
    "lastEmployer": "Eastdil Secured",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "13",
    "volume2025": "$390M+",
    "linkedin": "https://linkedin.com/in/sarah-kim-cre",
    "activityLevel": "High",
    "dealSignals": "$95M Seattle tech campus debt placement (Jan 2025)",
    "affiliations": "MBA, ULI, CCIM",
    "personalizationHook": "Recently placed $95M debt on a Seattle tech campus.",
    "confidence": "High",
    "evidenceNotes": "Eastdil team page and press releases.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Eastdil Secured Team",
        "url": "https://www.eastdilsecured.com/people/sarah-kim",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 90,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q20"
  },
  {
    "id": "evt-brk-021",
    "name": "Robert Hayes",
    "company": "Colliers Mortgage",
    "state": "CO",
    "city": "Denver",
    "email": "rhayes@colliers.com",
    "phone": "(303) 555-1157",
    "lastEmployer": "Colliers Mortgage",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "10",
    "volume2025": "Not Publicly Disclosed",
    "linkedin": "https://linkedin.com/in/robert-hayes-cre",
    "activityLevel": "Low",
    "dealSignals": "No recent deal signals found in last 12 months",
    "affiliations": "MBA",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Medium",
    "evidenceNotes": "Colliers team page confirms employment. Volume unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Volume not publicly disclosed; no recent deal signals",
    "rowStatus": "Review Required",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Colliers Team",
        "url": "https://www.colliers.com/en/people/robert-hayes",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 89,
    "sourcePlatform": "GRIP",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q01"
  },
  {
    "id": "evt-brk-022",
    "name": "Amanda Foster",
    "company": "Northmarq",
    "state": "MN",
    "city": "Minneapolis",
    "email": "afoster@northmarq.com",
    "phone": "(612) 555-1284",
    "lastEmployer": "Northmarq",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "8",
    "volume2025": "$140M",
    "linkedin": "https://linkedin.com/in/amanda-foster-cre",
    "activityLevel": "Medium",
    "dealSignals": "$22M multifamily agency loan (Jul 2024)",
    "affiliations": "MBA, ICSC",
    "personalizationHook": "Recently closed a $22M multifamily agency loan in Twin Cities.",
    "confidence": "High",
    "evidenceNotes": "Northmarq bio and Freddie Mac lender list.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Northmarq Profile",
        "url": "https://www.northmarq.com/people/amanda-foster",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 88,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q02"
  },
  {
    "id": "evt-brk-023",
    "name": "Thomas Wright",
    "company": "Greystone",
    "state": "NC",
    "city": "Charlotte",
    "email": "twright@greystone.com",
    "phone": "(704) 555-1392",
    "lastEmployer": "Unknown",
    "onlyCreMortgage": "Unverified \u2014 Manual Review",
    "yearsInCre": "Unknown",
    "volume2025": "Unknown",
    "linkedin": "Not Publicly Listed",
    "activityLevel": "Unknown",
    "dealSignals": "No deal signals found",
    "affiliations": "None identified",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Low",
    "evidenceNotes": "Only Tier 3 aggregator source found. Identity unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Identity unverified \u2014 only Tier 3 aggregator source",
    "rowStatus": "No Match",
    "scoreInputs": {
      "fullTimeCre": false,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "CRE Aggregator",
        "url": "https://www.loopnet.com/commercial-brokers/thomas-wright",
        "tier": 3
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 87,
    "sourcePlatform": "Brella",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q03"
  },
  {
    "id": "evt-brk-024",
    "name": "Lisa Nguyen",
    "company": "Arbor Realty Trust",
    "state": "NV",
    "city": "Las Vegas",
    "email": "lnguyen@arbor.com",
    "phone": "(702) 555-1468",
    "lastEmployer": "Arbor Realty Trust",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "6",
    "volume2025": "$75M",
    "linkedin": "https://linkedin.com/in/lisa-nguyen-cre",
    "activityLevel": "Medium",
    "dealSignals": "$15M multifamily loan (May 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Recently closed a $15M multifamily loan in Las Vegas.",
    "confidence": "Medium",
    "evidenceNotes": "Arbor team page verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Arbor Realty Team",
        "url": "https://www.arbor.com/team/lisa-nguyen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 86,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q04"
  },
  {
    "id": "evt-brk-025",
    "name": "Marcus Whitfield",
    "company": "CBRE Capital Markets",
    "state": "TX",
    "city": "Dallas",
    "email": "mwhitfield@cbre.com",
    "phone": "(214) 555-0182",
    "lastEmployer": "CBRE Capital Markets",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "18",
    "volume2025": "$450M+",
    "linkedin": "https://linkedin.com/in/marcuswhitfield-cre",
    "activityLevel": "High",
    "dealSignals": "Closed $85M Dallas office portfolio refi (Q1 2025); $42M industrial acquisition loan (Nov 2024)",
    "affiliations": "CCIM, MBA, ULI",
    "personalizationHook": "Recently closed an $85M Dallas office portfolio refinancing.",
    "confidence": "High",
    "evidenceNotes": "Verified via CBRE team page, NMLS, and LinkedIn.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "CBRE Team Page",
        "url": "https://www.cbre.com/people/marcus-whitfield",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 85,
    "sourcePlatform": "GRIP",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q05"
  }
];


const CALIBRATION_PRODUCERS = [
  { rank: 1, name: "Marcus W.", company: "CBRE Capital Markets", funded2025: "$412M", eventMatch: "High", calibrationScore: 94 },
  { rank: 2, name: "Jennifer A.", company: "JLL Debt Advisory", funded2025: "$318M", eventMatch: "High", calibrationScore: 92 },
  { rank: 3, name: "David K.", company: "Newmark", funded2025: "$285M", eventMatch: "High", calibrationScore: 91 },
  { rank: 4, name: "Sarah T.", company: "Walker & Dunlop", funded2025: "$276M", eventMatch: "Medium", calibrationScore: 89 },
  { rank: 5, name: "Robert H.", company: "Colliers", funded2025: "$241M", eventMatch: "High", calibrationScore: 88 },
  { rank: 6, name: "Michelle P.", company: "Eastdil Secured", funded2025: "$228M", eventMatch: "High", calibrationScore: 87 },
  { rank: 7, name: "James L.", company: "Marcus & Millichap", funded2025: "$205M", eventMatch: "Medium", calibrationScore: 85 },
  { rank: 8, name: "Angela M.", company: "Northmarq", funded2025: "$198M", eventMatch: "High", calibrationScore: 84 },
  { rank: 9, name: "Brian S.", company: "Greystone", funded2025: "$186M", eventMatch: "Medium", calibrationScore: 83 },
  { rank: 10, name: "Lisa R.", company: "Arbor Realty", funded2025: "$172M", eventMatch: "High", calibrationScore: 82 },
  { rank: 11, name: "Kevin D.", company: "Ready Capital", funded2025: "$165M", eventMatch: "Medium", calibrationScore: 80 },
];
[
  {
    "id": "evt-brk-001",
    "name": "Marcus Whitfield",
    "company": "CBRE Capital Markets",
    "state": "TX",
    "city": "Dallas",
    "email": "mwhitfield@cbre.com",
    "phone": "(214) 555-0182",
    "lastEmployer": "CBRE Capital Markets",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "18",
    "volume2025": "$450M+",
    "linkedin": "https://linkedin.com/in/marcuswhitfield-cre",
    "activityLevel": "High",
    "dealSignals": "Closed $85M Dallas office portfolio refi (Q1 2025); $42M industrial acquisition loan (Nov 2024)",
    "affiliations": "CCIM, MBA, ULI",
    "personalizationHook": "Recently closed an $85M Dallas office portfolio refinancing.",
    "confidence": "High",
    "evidenceNotes": "Verified via CBRE team page, NMLS, and LinkedIn.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "CBRE Team Page",
        "url": "https://www.cbre.com/people/marcus-whitfield",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 92,
    "sourcePlatform": "GRIP",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q01"
  },
  {
    "id": "evt-brk-002",
    "name": "Jennifer Alvarez",
    "company": "JLL Debt Advisory",
    "state": "CA",
    "city": "Los Angeles",
    "email": "jennifer.alvarez@jll.com",
    "phone": "(310) 555-0247",
    "lastEmployer": "JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "14",
    "volume2025": "$320M",
    "linkedin": "https://linkedin.com/in/jennifer-alvarez-cre",
    "activityLevel": "High",
    "dealSignals": "$62M multifamily bridge loan (Jan 2025); $28M retail center permanent financing (Sep 2024)",
    "affiliations": "MBA, ICSC, ULI",
    "personalizationHook": "Recently closed a $62M multifamily bridge loan in Southern California.",
    "confidence": "High",
    "evidenceNotes": "JLL bio page and California DRE license verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "JLL Bio Page",
        "url": "https://www.us.jll.com/en/people/jennifer-alvarez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 91,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q02"
  },
  {
    "id": "evt-brk-003",
    "name": "David Chen",
    "company": "Walker & Dunlop",
    "state": "NY",
    "city": "New York",
    "email": "dchen@walkerdunlop.com",
    "phone": "(212) 555-0391",
    "lastEmployer": "Walker & Dunlop",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "22",
    "volume2025": "$580M+",
    "linkedin": "https://linkedin.com/in/davidchen-cre",
    "activityLevel": "High",
    "dealSignals": "$120M Manhattan mixed-use refinancing (Feb 2025); Speaker at CREF Summit 2024",
    "affiliations": "CCIM, MBA, SIOR",
    "personalizationHook": "Speaker at CREF Summit 2024; closed $120M Manhattan mixed-use refinancing.",
    "confidence": "High",
    "evidenceNotes": "Walker & Dunlop team page and CREF Summit speaker listing.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Walker & Dunlop Team",
        "url": "https://www.walkerdunlop.com/team/david-chen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 90,
    "sourcePlatform": "Brella",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q03"
  },
  {
    "id": "evt-brk-004",
    "name": "Rachel Thompson",
    "company": "Newmark",
    "state": "FL",
    "city": "Miami",
    "email": "rthompson@nmrk.com",
    "phone": "(305) 555-0564",
    "lastEmployer": "Newmark",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "9",
    "volume2025": "$180M",
    "linkedin": "https://linkedin.com/in/rachel-thompson-cre",
    "activityLevel": "Medium",
    "dealSignals": "$35M hospitality acquisition loan (Dec 2024)",
    "affiliations": "MBA, ULI",
    "personalizationHook": "Recently closed a $35M hospitality acquisition loan in South Florida.",
    "confidence": "High",
    "evidenceNotes": "Newmark team page and Florida licensing verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Newmark Team Page",
        "url": "https://www.nmrk.com/people/rachel-thompson",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 89,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q04"
  },
  {
    "id": "evt-brk-005",
    "name": "Michael O'Brien",
    "company": "Berkadia",
    "state": "IL",
    "city": "Chicago",
    "email": "mobrien@berkadia.com",
    "phone": "(312) 555-0718",
    "lastEmployer": "Berkadia",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "16",
    "volume2025": "$275M",
    "linkedin": "https://linkedin.com/in/michael-obrien-cre",
    "activityLevel": "Medium",
    "dealSignals": "$48M affordable housing FHA loan (Oct 2024)",
    "affiliations": "MBA, CCIM",
    "personalizationHook": "Specializes in affordable housing FHA \u2014 closed $48M deal in Q4 2024.",
    "confidence": "High",
    "evidenceNotes": "Berkadia bio and HUD FHA announcement.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Berkadia Profile",
        "url": "https://www.berkadia.com/people/michael-obrien",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 88,
    "sourcePlatform": "GRIP",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q05"
  },
  {
    "id": "evt-brk-006",
    "name": "Priya Sharma",
    "company": "HFF (JLL)",
    "state": "GA",
    "city": "Atlanta",
    "email": "psharma@jll.com",
    "phone": "(404) 555-0833",
    "lastEmployer": "HFF / JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "11",
    "volume2025": "$210M",
    "linkedin": "https://linkedin.com/in/priya-sharma-cre",
    "activityLevel": "High",
    "dealSignals": "$55M industrial portfolio refinancing (Mar 2025)",
    "affiliations": "CCIM, SIOR, MBA",
    "personalizationHook": "Recently closed a $55M industrial portfolio refinancing in Atlanta.",
    "confidence": "High",
    "evidenceNotes": "JLL team page and CCIM member directory.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "JLL Team Page",
        "url": "https://www.us.jll.com/en/people/priya-sharma",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 87,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q06"
  },
  {
    "id": "evt-brk-007",
    "name": "James Rodriguez",
    "company": "Marcus & Millichap Capital",
    "state": "AZ",
    "city": "Phoenix",
    "email": "jrodriguez@marcusmillichap.com",
    "phone": "(602) 555-0946",
    "lastEmployer": "Marcus & Millichap",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "7",
    "volume2025": "$95M",
    "linkedin": "https://linkedin.com/in/james-rodriguez-cre",
    "activityLevel": "Medium",
    "dealSignals": "$18M self-storage acquisition financing (Aug 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Active in Phoenix self-storage \u2014 closed $18M acquisition financing.",
    "confidence": "Medium",
    "evidenceNotes": "M&M team page verified. Volume from partial disclosures.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "M&M Bio",
        "url": "https://www.marcusmillichap.com/advisors/james-rodriguez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 86,
    "sourcePlatform": "Brella",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q07"
  },
  {
    "id": "evt-brk-008",
    "name": "Sarah Kim",
    "company": "Eastdil Secured",
    "state": "WA",
    "city": "Seattle",
    "email": "skim@eastdil.com",
    "phone": "(206) 555-1029",
    "lastEmployer": "Eastdil Secured",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "13",
    "volume2025": "$390M+",
    "linkedin": "https://linkedin.com/in/sarah-kim-cre",
    "activityLevel": "High",
    "dealSignals": "$95M Seattle tech campus debt placement (Jan 2025)",
    "affiliations": "MBA, ULI, CCIM",
    "personalizationHook": "Recently placed $95M debt on a Seattle tech campus.",
    "confidence": "High",
    "evidenceNotes": "Eastdil team page and press releases.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Eastdil Secured Team",
        "url": "https://www.eastdilsecured.com/people/sarah-kim",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 85,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q08"
  },
  {
    "id": "evt-brk-009",
    "name": "Robert Hayes",
    "company": "Colliers Mortgage",
    "state": "CO",
    "city": "Denver",
    "email": "rhayes@colliers.com",
    "phone": "(303) 555-1157",
    "lastEmployer": "Colliers Mortgage",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "10",
    "volume2025": "Not Publicly Disclosed",
    "linkedin": "https://linkedin.com/in/robert-hayes-cre",
    "activityLevel": "Low",
    "dealSignals": "No recent deal signals found in last 12 months",
    "affiliations": "MBA",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Medium",
    "evidenceNotes": "Colliers team page confirms employment. Volume unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Volume not publicly disclosed; no recent deal signals",
    "rowStatus": "Review Required",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Colliers Team",
        "url": "https://www.colliers.com/en/people/robert-hayes",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 84,
    "sourcePlatform": "GRIP",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q09"
  },
  {
    "id": "evt-brk-010",
    "name": "Amanda Foster",
    "company": "Northmarq",
    "state": "MN",
    "city": "Minneapolis",
    "email": "afoster@northmarq.com",
    "phone": "(612) 555-1284",
    "lastEmployer": "Northmarq",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "8",
    "volume2025": "$140M",
    "linkedin": "https://linkedin.com/in/amanda-foster-cre",
    "activityLevel": "Medium",
    "dealSignals": "$22M multifamily agency loan (Jul 2024)",
    "affiliations": "MBA, ICSC",
    "personalizationHook": "Recently closed a $22M multifamily agency loan in Twin Cities.",
    "confidence": "High",
    "evidenceNotes": "Northmarq bio and Freddie Mac lender list.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Northmarq Profile",
        "url": "https://www.northmarq.com/people/amanda-foster",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 83,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q10"
  },
  {
    "id": "evt-brk-011",
    "name": "Thomas Wright",
    "company": "Greystone",
    "state": "NC",
    "city": "Charlotte",
    "email": "twright@greystone.com",
    "phone": "(704) 555-1392",
    "lastEmployer": "Unknown",
    "onlyCreMortgage": "Unverified \u2014 Manual Review",
    "yearsInCre": "Unknown",
    "volume2025": "Unknown",
    "linkedin": "Not Publicly Listed",
    "activityLevel": "Unknown",
    "dealSignals": "No deal signals found",
    "affiliations": "None identified",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Low",
    "evidenceNotes": "Only Tier 3 aggregator source found. Identity unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Identity unverified \u2014 only Tier 3 aggregator source",
    "rowStatus": "No Match",
    "scoreInputs": {
      "fullTimeCre": false,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "CRE Aggregator",
        "url": "https://www.loopnet.com/commercial-brokers/thomas-wright",
        "tier": 3
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 82,
    "sourcePlatform": "Brella",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q11"
  },
  {
    "id": "evt-brk-012",
    "name": "Lisa Nguyen",
    "company": "Arbor Realty Trust",
    "state": "NV",
    "city": "Las Vegas",
    "email": "lnguyen@arbor.com",
    "phone": "(702) 555-1468",
    "lastEmployer": "Arbor Realty Trust",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "6",
    "volume2025": "$75M",
    "linkedin": "https://linkedin.com/in/lisa-nguyen-cre",
    "activityLevel": "Medium",
    "dealSignals": "$15M multifamily loan (May 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Recently closed a $15M multifamily loan in Las Vegas.",
    "confidence": "Medium",
    "evidenceNotes": "Arbor team page verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Arbor Realty Team",
        "url": "https://www.arbor.com/team/lisa-nguyen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 81,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q12"
  },
  {
    "id": "evt-brk-013",
    "name": "Marcus Whitfield",
    "company": "CBRE Capital Markets",
    "state": "TX",
    "city": "Dallas",
    "email": "mwhitfield@cbre.com",
    "phone": "(214) 555-0182",
    "lastEmployer": "CBRE Capital Markets",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "18",
    "volume2025": "$450M+",
    "linkedin": "https://linkedin.com/in/marcuswhitfield-cre",
    "activityLevel": "High",
    "dealSignals": "Closed $85M Dallas office portfolio refi (Q1 2025); $42M industrial acquisition loan (Nov 2024)",
    "affiliations": "CCIM, MBA, ULI",
    "personalizationHook": "Recently closed an $85M Dallas office portfolio refinancing.",
    "confidence": "High",
    "evidenceNotes": "Verified via CBRE team page, NMLS, and LinkedIn.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "CBRE Team Page",
        "url": "https://www.cbre.com/people/marcus-whitfield",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 80,
    "sourcePlatform": "GRIP",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q13"
  },
  {
    "id": "evt-brk-014",
    "name": "Jennifer Alvarez",
    "company": "JLL Debt Advisory",
    "state": "CA",
    "city": "Los Angeles",
    "email": "jennifer.alvarez@jll.com",
    "phone": "(310) 555-0247",
    "lastEmployer": "JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "14",
    "volume2025": "$320M",
    "linkedin": "https://linkedin.com/in/jennifer-alvarez-cre",
    "activityLevel": "High",
    "dealSignals": "$62M multifamily bridge loan (Jan 2025); $28M retail center permanent financing (Sep 2024)",
    "affiliations": "MBA, ICSC, ULI",
    "personalizationHook": "Recently closed a $62M multifamily bridge loan in Southern California.",
    "confidence": "High",
    "evidenceNotes": "JLL bio page and California DRE license verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "JLL Bio Page",
        "url": "https://www.us.jll.com/en/people/jennifer-alvarez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 79,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q14"
  },
  {
    "id": "evt-brk-015",
    "name": "David Chen",
    "company": "Walker & Dunlop",
    "state": "NY",
    "city": "New York",
    "email": "dchen@walkerdunlop.com",
    "phone": "(212) 555-0391",
    "lastEmployer": "Walker & Dunlop",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "22",
    "volume2025": "$580M+",
    "linkedin": "https://linkedin.com/in/davidchen-cre",
    "activityLevel": "High",
    "dealSignals": "$120M Manhattan mixed-use refinancing (Feb 2025); Speaker at CREF Summit 2024",
    "affiliations": "CCIM, MBA, SIOR",
    "personalizationHook": "Speaker at CREF Summit 2024; closed $120M Manhattan mixed-use refinancing.",
    "confidence": "High",
    "evidenceNotes": "Walker & Dunlop team page and CREF Summit speaker listing.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Walker & Dunlop Team",
        "url": "https://www.walkerdunlop.com/team/david-chen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 78,
    "sourcePlatform": "Brella",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q15"
  },
  {
    "id": "evt-brk-016",
    "name": "Rachel Thompson",
    "company": "Newmark",
    "state": "FL",
    "city": "Miami",
    "email": "rthompson@nmrk.com",
    "phone": "(305) 555-0564",
    "lastEmployer": "Newmark",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "9",
    "volume2025": "$180M",
    "linkedin": "https://linkedin.com/in/rachel-thompson-cre",
    "activityLevel": "Medium",
    "dealSignals": "$35M hospitality acquisition loan (Dec 2024)",
    "affiliations": "MBA, ULI",
    "personalizationHook": "Recently closed a $35M hospitality acquisition loan in South Florida.",
    "confidence": "High",
    "evidenceNotes": "Newmark team page and Florida licensing verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Newmark Team Page",
        "url": "https://www.nmrk.com/people/rachel-thompson",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 77,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q16"
  },
  {
    "id": "evt-brk-017",
    "name": "Michael O'Brien",
    "company": "Berkadia",
    "state": "IL",
    "city": "Chicago",
    "email": "mobrien@berkadia.com",
    "phone": "(312) 555-0718",
    "lastEmployer": "Berkadia",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "16",
    "volume2025": "$275M",
    "linkedin": "https://linkedin.com/in/michael-obrien-cre",
    "activityLevel": "Medium",
    "dealSignals": "$48M affordable housing FHA loan (Oct 2024)",
    "affiliations": "MBA, CCIM",
    "personalizationHook": "Specializes in affordable housing FHA \u2014 closed $48M deal in Q4 2024.",
    "confidence": "High",
    "evidenceNotes": "Berkadia bio and HUD FHA announcement.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Berkadia Profile",
        "url": "https://www.berkadia.com/people/michael-obrien",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 76,
    "sourcePlatform": "GRIP",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q17"
  },
  {
    "id": "evt-brk-018",
    "name": "Priya Sharma",
    "company": "HFF (JLL)",
    "state": "GA",
    "city": "Atlanta",
    "email": "psharma@jll.com",
    "phone": "(404) 555-0833",
    "lastEmployer": "HFF / JLL",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "11",
    "volume2025": "$210M",
    "linkedin": "https://linkedin.com/in/priya-sharma-cre",
    "activityLevel": "High",
    "dealSignals": "$55M industrial portfolio refinancing (Mar 2025)",
    "affiliations": "CCIM, SIOR, MBA",
    "personalizationHook": "Recently closed a $55M industrial portfolio refinancing in Atlanta.",
    "confidence": "High",
    "evidenceNotes": "JLL team page and CCIM member directory.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": true,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "JLL Team Page",
        "url": "https://www.us.jll.com/en/people/priya-sharma",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 92,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q18"
  },
  {
    "id": "evt-brk-019",
    "name": "James Rodriguez",
    "company": "Marcus & Millichap Capital",
    "state": "AZ",
    "city": "Phoenix",
    "email": "jrodriguez@marcusmillichap.com",
    "phone": "(602) 555-0946",
    "lastEmployer": "Marcus & Millichap",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "7",
    "volume2025": "$95M",
    "linkedin": "https://linkedin.com/in/james-rodriguez-cre",
    "activityLevel": "Medium",
    "dealSignals": "$18M self-storage acquisition financing (Aug 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Active in Phoenix self-storage \u2014 closed $18M acquisition financing.",
    "confidence": "Medium",
    "evidenceNotes": "M&M team page verified. Volume from partial disclosures.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "M&M Bio",
        "url": "https://www.marcusmillichap.com/advisors/james-rodriguez",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 91,
    "sourcePlatform": "Brella",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q19"
  },
  {
    "id": "evt-brk-020",
    "name": "Sarah Kim",
    "company": "Eastdil Secured",
    "state": "WA",
    "city": "Seattle",
    "email": "skim@eastdil.com",
    "phone": "(206) 555-1029",
    "lastEmployer": "Eastdil Secured",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "13",
    "volume2025": "$390M+",
    "linkedin": "https://linkedin.com/in/sarah-kim-cre",
    "activityLevel": "High",
    "dealSignals": "$95M Seattle tech campus debt placement (Jan 2025)",
    "affiliations": "MBA, ULI, CCIM",
    "personalizationHook": "Recently placed $95M debt on a Seattle tech campus.",
    "confidence": "High",
    "evidenceNotes": "Eastdil team page and press releases.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "Eastdil Secured Team",
        "url": "https://www.eastdilsecured.com/people/sarah-kim",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "CRE Broker / Advisor",
    "qualificationScore": 90,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q20"
  },
  {
    "id": "evt-brk-021",
    "name": "Robert Hayes",
    "company": "Colliers Mortgage",
    "state": "CO",
    "city": "Denver",
    "email": "rhayes@colliers.com",
    "phone": "(303) 555-1157",
    "lastEmployer": "Colliers Mortgage",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "10",
    "volume2025": "Not Publicly Disclosed",
    "linkedin": "https://linkedin.com/in/robert-hayes-cre",
    "activityLevel": "Low",
    "dealSignals": "No recent deal signals found in last 12 months",
    "affiliations": "MBA",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Medium",
    "evidenceNotes": "Colliers team page confirms employment. Volume unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Volume not publicly disclosed; no recent deal signals",
    "rowStatus": "Review Required",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Colliers Team",
        "url": "https://www.colliers.com/en/people/robert-hayes",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 89,
    "sourcePlatform": "GRIP",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q01"
  },
  {
    "id": "evt-brk-022",
    "name": "Amanda Foster",
    "company": "Northmarq",
    "state": "MN",
    "city": "Minneapolis",
    "email": "afoster@northmarq.com",
    "phone": "(612) 555-1284",
    "lastEmployer": "Northmarq",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "8",
    "volume2025": "$140M",
    "linkedin": "https://linkedin.com/in/amanda-foster-cre",
    "activityLevel": "Medium",
    "dealSignals": "$22M multifamily agency loan (Jul 2024)",
    "affiliations": "MBA, ICSC",
    "personalizationHook": "Recently closed a $22M multifamily agency loan in Twin Cities.",
    "confidence": "High",
    "evidenceNotes": "Northmarq bio and Freddie Mac lender list.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": true,
      "strongNetwork": false,
      "contentCreator": false,
      "dealVolumeMedium": true
    },
    "evidenceSources": [
      {
        "label": "Northmarq Profile",
        "url": "https://www.northmarq.com/people/amanda-foster",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 88,
    "sourcePlatform": "Swapcard",
    "priorityTier": "Priority",
    "eventAttendeeId": "evt-q02"
  },
  {
    "id": "evt-brk-023",
    "name": "Thomas Wright",
    "company": "Greystone",
    "state": "NC",
    "city": "Charlotte",
    "email": "twright@greystone.com",
    "phone": "(704) 555-1392",
    "lastEmployer": "Unknown",
    "onlyCreMortgage": "Unverified \u2014 Manual Review",
    "yearsInCre": "Unknown",
    "volume2025": "Unknown",
    "linkedin": "Not Publicly Listed",
    "activityLevel": "Unknown",
    "dealSignals": "No deal signals found",
    "affiliations": "None identified",
    "personalizationHook": "No personalization signal found.",
    "confidence": "Low",
    "evidenceNotes": "Only Tier 3 aggregator source found. Identity unverified.",
    "manualReviewFlag": true,
    "manualReviewReason": "Identity unverified \u2014 only Tier 3 aggregator source",
    "rowStatus": "No Match",
    "scoreInputs": {
      "fullTimeCre": false,
      "activeDealmaker": false,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "CRE Aggregator",
        "url": "https://www.loopnet.com/commercial-brokers/thomas-wright",
        "tier": 3
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 87,
    "sourcePlatform": "Brella",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q03"
  },
  {
    "id": "evt-brk-024",
    "name": "Lisa Nguyen",
    "company": "Arbor Realty Trust",
    "state": "NV",
    "city": "Las Vegas",
    "email": "lnguyen@arbor.com",
    "phone": "(702) 555-1468",
    "lastEmployer": "Arbor Realty Trust",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "6",
    "volume2025": "$75M",
    "linkedin": "https://linkedin.com/in/lisa-nguyen-cre",
    "activityLevel": "Medium",
    "dealSignals": "$15M multifamily loan (May 2024)",
    "affiliations": "MBA",
    "personalizationHook": "Recently closed a $15M multifamily loan in Las Vegas.",
    "confidence": "Medium",
    "evidenceNotes": "Arbor team page verified.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Partial",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": false,
      "usesTechnology": false,
      "strongNetwork": false,
      "contentCreator": false
    },
    "evidenceSources": [
      {
        "label": "Arbor Realty Team",
        "url": "https://www.arbor.com/team/lisa-nguyen",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 86,
    "sourcePlatform": "Broker Directory",
    "priorityTier": "Nurture",
    "eventAttendeeId": "evt-q04"
  },
  {
    "id": "evt-brk-025",
    "name": "Marcus Whitfield",
    "company": "CBRE Capital Markets",
    "state": "TX",
    "city": "Dallas",
    "email": "mwhitfield@cbre.com",
    "phone": "(214) 555-0182",
    "lastEmployer": "CBRE Capital Markets",
    "onlyCreMortgage": "Yes",
    "yearsInCre": "18",
    "volume2025": "$450M+",
    "linkedin": "https://linkedin.com/in/marcuswhitfield-cre",
    "activityLevel": "High",
    "dealSignals": "Closed $85M Dallas office portfolio refi (Q1 2025); $42M industrial acquisition loan (Nov 2024)",
    "affiliations": "CCIM, MBA, ULI",
    "personalizationHook": "Recently closed an $85M Dallas office portfolio refinancing.",
    "confidence": "High",
    "evidenceNotes": "Verified via CBRE team page, NMLS, and LinkedIn.",
    "manualReviewFlag": false,
    "manualReviewReason": "",
    "rowStatus": "Complete",
    "scoreInputs": {
      "fullTimeCre": true,
      "activeDealmaker": true,
      "independent": false,
      "nationalFocus": true,
      "usesTechnology": true,
      "strongNetwork": true,
      "contentCreator": false,
      "dealVolumeHigh": true
    },
    "evidenceSources": [
      {
        "label": "CBRE Team Page",
        "url": "https://www.cbre.com/people/marcus-whitfield",
        "tier": 1
      }
    ],
    "leadSource": "Event \u2014 CRE Finance Summit 2025",
    "classification": "Lender / Capital Markets",
    "qualificationScore": 85,
    "sourcePlatform": "GRIP",
    "priorityTier": "Low Priority",
    "eventAttendeeId": "evt-q05"
  }
];


const CALIBRATION_PRODUCERS = [
  { rank: 1, name: "Marcus W.", company: "CBRE Capital Markets", funded2025: "$412M", eventMatch: "High", calibrationScore: 94 },
  { rank: 2, name: "Jennifer A.", company: "JLL Debt Advisory", funded2025: "$318M", eventMatch: "High", calibrationScore: 92 },
  { rank: 3, name: "David K.", company: "Newmark", funded2025: "$285M", eventMatch: "High", calibrationScore: 91 },
  { rank: 4, name: "Sarah T.", company: "Walker & Dunlop", funded2025: "$276M", eventMatch: "Medium", calibrationScore: 89 },
  { rank: 5, name: "Robert H.", company: "Colliers", funded2025: "$241M", eventMatch: "High", calibrationScore: 88 },
  { rank: 6, name: "Michelle P.", company: "Eastdil Secured", funded2025: "$228M", eventMatch: "High", calibrationScore: 87 },
  { rank: 7, name: "James L.", company: "Marcus & Millichap", funded2025: "$205M", eventMatch: "Medium", calibrationScore: 85 },
  { rank: 8, name: "Angela M.", company: "Northmarq", funded2025: "$198M", eventMatch: "High", calibrationScore: 84 },
  { rank: 9, name: "Brian S.", company: "Greystone", funded2025: "$186M", eventMatch: "Medium", calibrationScore: 83 },
  { rank: 10, name: "Lisa R.", company: "Arbor Realty", funded2025: "$172M", eventMatch: "High", calibrationScore: 82 },
  { rank: 11, name: "Kevin D.", company: "Ready Capital", funded2025: "$165M", eventMatch: "Medium", calibrationScore: 80 },
];
